### ISSUE TITLE
learning plans

### ISSUE THREAD

**Issue by RoniPerson** [TKFRvisionOfficial/lernsax-webweaver-api-research#1]
Do you know if there is any way to access the learning plans? I got it working for tasks but `set_focus` don't works with `"object": "learning_plans"`.

**Comment by TKFRvisionOfficial** [comment]
sry for taking such a long time to respond. your issue must have slipped under my radar. have you figured it out by now? what is the german name for learning plan? because not every school has the same features I dont know if I even have this feature. The only things I have is:

_german name: internal name_
Lerntagebuch: learning_log
Lernmodule: courselets
Lernerfolgskontrolle: courses (I am not sure about that one)

**Comment by RoniPerson** [comment]
The german name is "Lernplan". But if it isn't available for your school, I will close the issue and see if I can find something my self.
